apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/actions-runner-controller/actions-runner-controller.git
    targetRevision: 0.27.6
    chart: actions-runner-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
